### ISSUE TITLE
 Lift Aeson upper bound

### ISSUE THREAD

**Issue by koterpillar** [seagreen/hjsonpointer#8]
This package no longer builds with LTS 13 due to the Aeson <1.4 requirement. Would be nice to get it into the LTS or at least make it compatible.

There are no upper bounds in the Cabal file on GitHub, but the bound is present on Hackage.

**Comment by seagreen** [comment]
Done in revision 3: http://hackage.haskell.org/package/hjsonpointer-1.5.0/revisions/
